---

- name: Install mod_auth_openidc from centos standard repository
  shell: yum -y install mod_auth_openidc warn=false

- name: Link mod_auth_openidc to custom httpd24 modules location
  file:
    src: '/etc/httpd/modules/mod_auth_openidc.so'
    dest: '{{ httpd24_conf_root_path }}/modules/mod_auth_openidc.so'
    state: link

- import_role:
    name: apache-virtualhost
  vars:
    template_path: ../provision_proxy/templates/custom_httpd.conf
  tags:
    - update_proxy_apache_config
