---

- name: Make sure we have a 'wheel' group
  group: name=wheel state=present

- name: Add users that should be able to log in to OS
  user: name=nkr-user groups=wheel append=yes state=present createhome=yes

- include_role:
    name: python
  vars:
    owner_user: "{{ nkr_user }}"
    owner_group: "{{ nkr_user }}"

- import_tasks: apache.yml

- name: Display additional instructions for local dev environment
  debug:
    msg:
      - "Local dev environment successfully set up. Execute `vagrant ssh` to connect."
      - "For web browser access, open your local /etc/hosts file and add the following entries:"
      - "30.30.30.30 nkr-index.csc.local"
      - "30.30.30.30 nkr-harvester.csc.local"
      - "30.30.30.30 nkr-proxy.csc.local"
  when: deployment_environment_id == 'local_development'
