---

- name: Make sure we have a 'wheel' group
  group: name=wheel state=present

- name: Add users that should be able to log in to OS
  user: name=nkr-user groups=wheel append=yes state=present createhome=yes

- name: Add index hosts to /etc/hosts
  import_role:
    name: etc_hosts
  vars:
    ip_list: "{{ index_ip_list }}"
    host_list: "{{ index_host_list }}"
  when: deployment_environment_id in ['test', 'pentest']

- name: Install Redis
  import_role:
    name: redis

- name: Install python
  import_role:
    name: python
  vars:
    owner_user: "{{ nkr_user }}"
    owner_group: "{{ nkr_user }}"

- name: Install flask web app
  import_role:
    name: flask
  vars:
    owner_user: "{{ nkr_user }}"
    owner_group: "{{ nkr_user }}"
    app_name: "{{ nkr_app_name }}"
    app_base_path: "{{ nkr_proxy_app_base_path }}"
    python_venv_path: "{{ python_virtualenv_path }}"

- name: Install gunicorn
  import_role:
    name: gunicorn
  vars:
    owner_user: "{{ nkr_user }}"
    owner_group: "{{ nkr_user }}"
    app_user: "{{ nkr_user }}"
    app_name: "{{ nkr_app_name }}"
    app_base_path: "{{ nkr_proxy_app_base_path }}"
    working_dir: "{{ nkr_proxy_web_app_src_path }}"
    pythonpath: "{{ nkr_proxy_web_app_src_path }}"
    python_venv_path: "{{ python_virtualenv_path }}"

- import_tasks: apache.yml

- block:
  - name: Copy bash aliases to {{ nkr_user }} user home dir
    template: src=templates/bash_proxy_aliases dest=/home/{{ nkr_user }}/.bash_proxy_aliases owner={{ nkr_user }} group={{ nkr_user }}

  - name: Touch {{ nkr_user }} .bash_profile
    file: path=/home/{{ nkr_user }}/.bash_profile owner={{ nkr_user }} group={{ nkr_user }} state=touch

  - name: Add printing of bash aliases to {{ nkr_user }} profile
    lineinfile:
      dest: "/home/{{ nkr_user }}/.bash_profile"
      state: present
      line: "{{ item }}"
    with_items:
      - "source .bash_proxy_aliases"
      - "aliases"

  when: deployment_environment_id in ['local_development', 'test', 'stable']

- name: Install cron job to check and close user sessions
  import_tasks: cron.yml
  tags:
    - cron_only

- block

  - name: Display additional instructions for local dev environment
    debug:
      msg:
        - "Local dev environment successfully set up. Execute `vagrant ssh` to connect."
        - "For web browser access, open your local /etc/hosts file and add the following entries:"
        - "30.30.30.30 nkr-index.csc.local"
        - "30.30.30.30 nkr-harvester.csc.local"
        - "30.30.30.30 nkr-proxy.csc.local"

  - name: Add proxy local host to /etc/hosts
    lineinfile:
      dest: "/etc/hosts"
      state: present
      line: "30.30.30.30 {{ server_domain_name }}"

  when: deployment_environment_id == 'local_development'
