---

# "secrets" for local development use

secrets:

  indexservers:
    server_domain_name: nkr-index.csc.local
    solr:
        port: "8983"
        version: "6.2.0"
    httpd:
        conf_loglevel: debug
        listen_port: 443
        intermediate_certificate_name: not_used
        ba_users:
            - { username: nkr-index, password: nkr-index }

  proxyservers:
    server_domain_name: nkr-proxy.csc.local
    flask_app:
        debug: 1
        log_level: DEBUG
        rems_url: https://rems.somewhere.org/api/entitlements
        rems_api_key: rems_api_key
        index_url: https://localhost:8983/solr
        index_name: index_name
        index_username: not_used
        index_password: not_used
        level_restriction_field: display_restriction_id_str
        document_unique_id_field: _document_id
    httpd:
        conf_loglevel: debug
        listen_port: 443
        intermediate_certificate_name: not_used
        ba_users:
            - { username: nkr-proxy, password: nkr-proxy }
