---

# "secrets" for local development use

secrets:

    indexservers:
        solr:
            port: "8983"
            version: "6.2.0"
            solr_java_mem: "-Xms512m -Xmx512m"
        solr_cluster: false
        finna_solr_commit: b319000b24896b4744eb60a34c47e7898bb113f7
        zookeeper:
            client_port: 2181
        httpd:
            conf_loglevel: debug
            listen_port: 443
            intermediate_certificate_name: not_used
            ba_users:
                - { username: nkr-index, password: nkr-index }

    proxyservers:
        server_domain_name: nkr-proxy.csc.local
        flask_app:
            debug: 1
            log_level: DEBUG
            verify_tls: 0
            rems_host: rems.somewhere.org
            rems_api_key: rems_api_key
            rems_rejecter_bot_user: 'rejecter-bot'
            index_hosts:
                - localhost:8983
            index_main_api: /solr
            index_name: biblio
            index_username: not_used
            index_password: not_used
            index_allowed_apis: select
            level_restriction_field: display_restriction_id_str
            document_unique_id_field: _document_id
            metadata_level_10_resource_id: metadata-level::10
        cache:
            host: localhost
            port: 6379
            password: null
        session_check:
            rems_session_close_user: 'nkr-session-bot'
        httpd:
            conf_loglevel: debug
            listen_port: 443
            intermediate_certificate_name: not_used
            ba_users:
                - { username: nkr-proxy, password: nkr-proxy }

    harvesterservers:
        repository_base_url: base.url
        admin_email: nobody@localhost
        index:
            index_hostname: localhost
            index_port: 8983
            index_name: biblio
            index_username: not_used
            index_password: not_used
        datasource:
            url: <copy_these_from_nkr-ops-sec_secrets_for_test>
            username: dummy
            password: dummy
