---

# "secrets" for local development use

secrets:

  indexservers:
    server_domain_name: nkr-index.csc.local
    solr:
        port: "8983"
        version: "6.2.0"
    solr_cluster: false
    httpd:
        conf_loglevel: debug
        listen_port: 443
        intermediate_certificate_name: not_used
        ba_users:
            - { username: nkr-index, password: nkr-index }

  proxyservers:
    server_domain_name: nkr-proxy.csc.local
    flask_app:
        debug: 1
        log_level: DEBUG
        verify_tls: 0
        rems_host: rems.somewhere.org
        rems_api_key: rems_api_key
        rems_rejecter_bot_user: 'rejecter-bot'
        index_url: http://localhost:8983/solr
        index_ip_list: null
        index_main_api: null
        index_hostname: null
        index_name: biblio
        index_username: not_used
        index_password: not_used
        index_allowed_apis: select
        level_restriction_field: display_restriction_id_str
        document_unique_id_field: _document_id
        metadata_level_10_resource_id: metadata-level::10
    cache:
        host: localhost
        port: 6379
        password: null
    session_check:
        rems_session_close_user: 'nkr-session-bot'
    httpd:
        conf_loglevel: debug
        listen_port: 443
        intermediate_certificate_name: not_used
        ba_users:
            - { username: nkr-proxy, password: nkr-proxy }
