---

# secrets template for non-local envs

secrets:

    # usernames should have matching public keys in files/public_keys e.g. username1.pub
    os_users:
        - username1

    indexservers:
        server_domain_name: host1.org
        external_ips:
            - 12.34.56.78
        internal_ips:
            - 192.168.1.1
        solr:
            port: "port_as_string"
            version: "version_number"
        httpd:
            conf_loglevel: debug
            listen_port: 443
            intermediate_certificate_name: cert_name.crt
            ba_users:
                # let these users access the index
                - { username: index_user, password: index_pass }

    proxyservers:
        server_domain_name: host2.org
        external_ips:
            - 12.34.56.79
        internal_ips:
            - 192.168.1.2
        flask_app:
            debug: 1
            log_level: DEBUG
            rems_url: http://rems2_host.org/api/entitlements
            rems_api_key: api_key
            index_url: https://index_host.org
            index_name: index_name
            index_username: index_user
            index_password: index_pass
            # name of the field in indexed documents which contains restriction level, e.g. 10, 20, 30
            level_restriction_field: display_restriction_id_str
            # name of the field in indexed documents which is the unique id, and matches the rems entitlement id
            document_unique_id_field: _document_id
        httpd:
            conf_loglevel: debug
            listen_port: 443
            intermediate_certificate_name: cert_name.crt
            ba_users:
                # let these users access the proxy
                - { username: proxy_user, password: proxy_pass }
