---

# note: this role is executed by role os-base

- block:

    - name: Make sure we have a 'wheel' group
      group: name=wheel state=present

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'

    - name: Add users that should be able to log in to OS
      user: name={{ item }} groups=wheel append=yes state=present createhome=yes
      with_items: "{{ os_users }}"

    - name: Create .ssh folders to login users' home folders in cloud environment
      file: path=/home/{{ item }}/.ssh owner={{ item }} mode=0700 state=directory
      with_items: "{{ os_users }}"

    - name: Add login users' public keys to cloud environment
      copy: src=files/public_keys/{{ item }}.pub dest=/home/{{ item }}/.ssh/authorized_keys owner={{ item }} mode=0600
      with_items: "{{ os_users }}"

    - name: Determine existing users
      shell: 'grep wheel /etc/group | cut -d: -f4 | tr "," "\n"'
      changed_when: false
      register: existing_users

    - name: Determine removed users
      set_fact:
        removed_users: "{{ existing_users.stdout_lines | difference(ssh_user) | difference(os_users) | difference (nkr_user) }}"

    - name: Delete removed user accounts
      user:
        name: "{{ item }}"
        state: absent
      with_items: "{{ removed_users }}"

  when: deployment_environment_id != 'local_development'
