
- name: Install solr
  import_role:
    name: finna-solr

- name: Install httpd
  import_role:
    name: apache-virtualhost
  vars:  
      template_path: ../provision_index/templates/custom_httpd.conf
