---

- name: Install zookeeper using ansible-zookeeper role
  include_role:
    name: ansible-zookeeper
  vars:
    data_dir: /data/zookeeper
    # newer version has "apache-" prefix in .tar.gz filename
    zookeeper_url: http://www.us.apache.org/dist/zookeeper/zookeeper-{{zookeeper_version}}/apache-zookeeper-{{zookeeper_version}}-bin.tar.gz
    zookeeper_version: 3.5.5
    client_port: "{{ zookeeper.client_port }}"
    zookeeper_hosts: "
    {%- set ips = [] %}
    {%- for host in groups['indexservers'] %}
    {{- ips.append(dict(id=loop.index, host=host, ip=hostvars[host]['ansible_default_ipv4'].address)) }}
    {%- endfor %}
    {{- ips -}}"
    zookeeper_env: {
      "JAVA_HOME": "{{ ansible_local['java']['general']['home'] }}"
    }

- name: Start zookeeper service
  service: name=zookeeper state=restarted
  tags: deploy
