---

- name: Install zookeeper using ansible-zookeeper role
  include_role:
    name: ansible-zookeeper
  vars:
    data_dir: /data/zookeeper
    zookeeper_version: 3.4.14
    zookeeper_hosts: "
    {%- set ips = [] %}
    {%- for host in groups['indexservers'] %}
    {{- ips.append(dict(id=loop.index, host=host, ip=hostvars[host]['ansible_default_ipv4'].address)) }}
    {%- endfor %}
    {{- ips -}}"
    zookeeper_env: {
      "JAVA_HOME": "{{ ansible_local['java']['general']['home'] }}"
    }

- name: Start zookeeper service
  service: name=zookeeper state=restarted
  tags: deploy
