---

- name: Create directory for SSL certificates
  file: path={{ httpd.ssl_certificates_path }} state=directory
  when: deployment_environment_id in ['local_development', 'test']
  # when: deployment_environment_id in ['local_development', 'test', 'stable', 'staging']

- name: Create self-signed SSL cert and private key
  command: openssl req -x509 -nodes -subj "/C=FI/ST=Uusimaa/L=Espoo/O=CSC/CN={{ httpd.server_domain_name }}" -days 365 -newkey rsa:2048 -keyout {{ httpd.ssl_certificates_path }}/{{ httpd.ssl_key_name }} -out {{ httpd.ssl_certificates_path }}/{{ httpd.ssl_certificate_name }} creates={{ httpd.ssl_certificates_path }}/{{ httpd.ssl_certificate_name }}
  when: deployment_environment_id == 'local_development'

- block:

    - name: Install dos2unix
      shell: yum -y install dos2unix warn=false

    - name: Copy CA-signed primary certificate and private key
      copy: src=files/certificates/{{ item }} dest={{ httpd.ssl_certificates_path }}/{{ item }} owner=root group=root mode=0644
      with_items:
        - "{{ httpd.ssl_certificate_name }}"
        - "{{ httpd.ssl_key_name }}"

    - name: Concatenate intermediate certificate to primary certificate
      lineinfile:
        line: "{{ lookup('file', 'files/certificates/{{ httpd.intermediate_certificate_name }}') }}"
        dest: "{{ httpd.ssl_certificates_path }}/{{ httpd.ssl_certificate_name }}"
        state: present

    - name: Fix concatenated file carriage returns
      command: dos2unix {{ httpd.ssl_certificates_path }}/{{ httpd.ssl_certificate_name }}

  when: deployment_environment_id in ['test', 'stable']
