---

- name: Install selinux python3 bindings
  pip: name=selinux state=latest executable=pip3

- name: Copy a pip.conf file to /etc
  template: src=templates/pip.conf dest=/etc/pip.conf

- name: Make sure we have a 'nkr' group in OS
  group: name=nkr state=present

- name: Disable SSH password authentication
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
  when: deployment_environment_id != 'local_development'
  notify: restart sshd

- name: Install common yum packages
  shell: yum -y install gcc gcc-c++ git curl vim nano zip unzip tree screen warn=false

- name: Install common os packages for development
  shell: yum -y install tcl ntp warn=false
  when: deployment_environment_id not in ['production']

- block:

    - name: Set SELinux to permissive in current session
      shell: setenforce 0

    - name: Set SELinux to permissive in /etc/selinux/config
      lineinfile:
        dest: /etc/selinux/config
        regexp: SELINUX=enforcing
        line: SELINUX=permissive
        state: present

  when: deployment_environment_id != 'production'

- name: Reinstall glibc-common just in case to make Finnish locale available using yum
  shell: yum -y reinstall glibc-common warn=false
  when: deployment_environment_id == 'local_development'

- name: Set locale LANG to en_US.UTF-8
  shell: localectl set-locale LANG=en_US.UTF-8

- name: Set default locale as LC_ALL to fi_FI.UTF-8
  lineinfile:
    dest: /etc/environment
    state: present
    line: "LC_ALL=\"fi_FI.UTF-8\""

- name: Set default locale as LC_CTYPE to fi_FI.UTF-8
  lineinfile:
    dest: /etc/environment
    state: present
    line: "LC_CTYPE=\"fi_FI.UTF-8\""

- name: Set timezone to Europe/Helsinki
  timezone:
    name: Europe/Helsinki

- include_role: name=users
  when: deployment_environment_id != 'production'

- include_role: name=update_packages
