---

- name: Yum update
  yum:
    name: "*"
    state: latest
    update_cache: yes

- name: Install stuff from Yum
  yum:
    name:
      - epel-release
      - libffi-devel
      - openssl-devel
      - git
      - python3
      - python3-devel
    state: latest

- name: Upgrade global pip3
  pip:
    executable: pip3
    extra_args: --upgrade
    name: pip
