---

- hosts: proxyservers
  become: yes
  roles:
    - flask
  vars:
    owner_user: "{{ nkr_user }}"
    owner_group: "{{ nkr_user }}"
    app_name: "{{ nkr_app_name }}"
    app_base_path: "{{ nkr_proxy_app_base_path }}"
    python_venv_path: "{{ python_virtualenv_path }}"
  tasks:
    - name: Restart gunicorn
      service: name=gunicorn state=restarted
