---

- hosts: indexservers
  become: yes
  roles:
    - { role: preprovision, when: "deployment_environment_id == 'local_development'" }
    - os-base
    - apache
    - ansible-role-java
    - zookeeper
    - provision_index
  vars:
    java_version: 'jdk-11.0.6+10'
