---

- hosts: proxyservers
  become: yes
  roles:
    - flask_app_config

- hosts: proxyservers
  become: yes
  tasks:
    - name: Restart gunicorn
      service:
        name: gunicorn
        state: restarted
      when: deployment_environment_id != 'local_development'
